services:

  postgres:
    image: pgvector/pgvector:pg15
    container_name: pdftalk-postgres

    environment:
      POSTGRES_DB: pdftalk
      POSTGRES_USER: pdftalk
      POSTGRES_PASSWORD: 3wYd8pmybim4JXe8vmmNQf37zzpY0Oll     # pragma: allowlist secret

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdftalk"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: pdftalk-redis
    command: redis-server --requirepass FCVPvJkWzjPrVGhHBkENqxR4lzo36hCV --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal

  api:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    environment:
      ENV_FILE: .env.docker   # tells config.py which file to load
    env_file:
      - ./backend/.env.docker

    volumes:
      - ./backend:/app
      - /app/.venv
      - prometheus_multiproc:/tmp/prometheus_multiproc

    command: >
      .venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - internal

  worker:
    build:
      context: ./backend

    environment:
      ENV_FILE: .env.docker
    env_file:
      - ./backend/.env.docker

    volumes:
      - ./backend:/app
      - /app/.venv
      - prometheus_multiproc:/tmp/prometheus_multiproc

    command: .venv/bin/python -m app.workers.worker

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    networks:
      - internal

  nginx:
    image: nginx:alpine

    volumes:
      - ./infra/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "80:80"

    depends_on:
      - api

    networks:
      - internal
      - external

volumes:
  postgres_data:
  redis_data:
  prometheus_multiproc:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  internal:
    driver: bridge

  external:
    driver: bridge
